#cloud-config
package_update: true
package_upgrade: true

packages:
  - apache2
  - openssl

runcmd:

  #Enable ssl module
  - a2enmod ssl
  
  # Enable the default SSL site
  - a2ensite default-ssl

  # Restart Apache to apply the changes
  - systemctl restart apache2
  - systemctl enable apache2

